"use client";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect } from 'react'
import TopBar from './components/TopBar';
// import TopBar from '.TopBar/components/TopBar';
import NavBar from './components/NavBar';
import Footer from './components/Footer';
import AOS from 'aos';
import 'aos/dist/aos.css';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      duration: 800,
      once: true
    })
  }, [])
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <TopBar />
        <NavBar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}